package bot.seven.WLR.gui

import java.awt.Color

object GuiColors {
    val PRIMARY_RED: Int = Color(200, 30, 30).rgb
    val PRIMARY_RED_BRIGHT: Int = Color(255, 80, 80).rgb
    val PRIMARY_RED_DARK: Int = Color(150, 20, 20).rgb
    val LIGHT_RED: Int = Color(255, 100, 100).rgb

    val SCREEN_BACKGROUND: Int = Color(25, 25, 28).rgb
    val COMPONENT_BACKGROUND: Int = Color(45, 45, 50).rgb
    val COMPONENT_BACKGROUND_HOVER: Int = Color(60, 60, 65).rgb
    val COMPONENT_BACKGROUND_DISABLED: Int = Color(35, 35, 40).rgb
    val COMPONENT_BORDER: Int = Color(70, 70, 75).rgb

    val TEXT_PRIMARY: Int = Color(220, 220, 225).rgb
    val TEXT_SECONDARY: Int = Color(180, 180, 180).rgb
    val TEXT_ACCENT: Int = PRIMARY_RED_BRIGHT
    val TEXT_DISABLED: Int = Color(100, 100, 105).rgb

    val TAB_BAR_BACKGROUND: Int = Color(35, 35, 40).rgb
    val TAB_BUTTON_BACKGROUND_INACTIVE: Int = TAB_BAR_BACKGROUND
    val TAB_BUTTON_BACKGROUND_HOVER: Int = COMPONENT_BACKGROUND_HOVER
    val TAB_BUTTON_BACKGROUND_ACTIVE: Int = PRIMARY_RED
    val TAB_BUTTON_TEXT_INACTIVE: Int = Color(160, 160, 165).rgb
    val TAB_BUTTON_TEXT_HOVER: Int = TEXT_PRIMARY
    val TAB_BUTTON_TEXT_ACTIVE: Int = TEXT_PRIMARY
    val TAB_BAR_BORDER: Int = Color(55, 55, 60).rgb
    val TAB_SCROLL_BUTTON_BG: Int = Color(60, 60, 65).rgb
    val TAB_SCROLL_BUTTON_HOVER_BG: Int = Color(80, 80, 85).rgb
    val TAB_SCROLL_BUTTON_ARROW: Int = TEXT_PRIMARY

    val CATEGORY_TITLE_TEXT: Int = Color(240, 240, 245).rgb
    val CATEGORY_TITLE_BACKGROUND: Int = Color(80, 30, 30, 230).rgb
    val CATEGORY_TITLE_BORDER: Int = Color(120, 50, 50, 200).rgb
    val CATEGORY_SEPARATOR_LINE: Int = Color(100, 40, 40, 180).rgb

    val SCROLLBAR_BG: Int = Color(35, 35, 40).rgb
    val SCROLLBAR_THUMB: Int = PRIMARY_RED

    val CHECKBOX_BOX: Int = COMPONENT_BACKGROUND
    val CHECKBOX_BOX_HOVER: Int = COMPONENT_BACKGROUND_HOVER
    val CHECKBOX_CHECK: Int = PRIMARY_RED_BRIGHT
    val DARK_RED: Int = PRIMARY_RED_DARK

    val DROPDOWN_ARROW: Int = TEXT_PRIMARY
    val DROPDOWN_BACKGROUND_OPEN: Int = Color(30, 30, 35, 245).rgb
    val DROPDOWN_ITEM_TEXT: Int = TEXT_PRIMARY
    private val _PRIMARY_RED_AWT = Color(PRIMARY_RED, false)
    val DROPDOWN_ITEM_HOVER_BG: Int = Color(_PRIMARY_RED_AWT.red, _PRIMARY_RED_AWT.green, _PRIMARY_RED_AWT.blue, 70).rgb
    val DROPDOWN_ITEM_SELECTED_BG: Int = Color(_PRIMARY_RED_AWT.red, _PRIMARY_RED_AWT.green, _PRIMARY_RED_AWT.blue, 100).rgb

    val SLIDER_TRACK: Int = Color(55, 55, 60).rgb
    val SLIDER_TRACK_FILLED: Int = PRIMARY_RED
    val SLIDER_KNOB: Int = Color(190, 190, 195).rgb
    val SLIDER_KNOB_HOVER: Int = Color(220, 220, 225).rgb

    val TEXTFIELD_BACKGROUND: Int = Color(30, 30, 35).rgb
    val TEXTFIELD_BORDER: Int = COMPONENT_BORDER
    val TEXTFIELD_BORDER_FOCUSED: Int = PRIMARY_RED_BRIGHT
    val TEXTFIELD_TEXT: Int = TEXT_PRIMARY

    val MODERN_PRIMARY_BACKGROUND: Int = SCREEN_BACKGROUND
    val MODERN_SECONDARY_BACKGROUND: Int = COMPONENT_BACKGROUND

    val MODERN_ACCENT_PRIMARY: Int = PRIMARY_RED_BRIGHT
    val MODERN_ACCENT_SECONDARY: Int = PRIMARY_RED

    val MODERN_BORDER_COLOR: Int = COMPONENT_BORDER
    val MODERN_DIVIDER_COLOR: Int = Color(50, 50, 55).rgb

    val MODERN_COMPONENT_HOVER: Int = COMPONENT_BACKGROUND_HOVER
    val MODERN_COMPONENT_ACTIVE: Int = LIGHT_RED
    val MODERN_COMPONENT_DISABLED_BG: Int = COMPONENT_BACKGROUND_DISABLED

    val MODERN_SCROLLBAR_BG: Int = SCROLLBAR_BG
    val MODERN_SCROLLBAR_THUMB: Int = SCROLLBAR_THUMB
    val MODERN_SCROLLBAR_THUMB_HOVER: Int = PRIMARY_RED_BRIGHT

    val BUTTON_MODERN_BACKGROUND: Int = PRIMARY_RED
    val BUTTON_MODERN_BACKGROUND_HOVER: Int = PRIMARY_RED_BRIGHT
    val BUTTON_MODERN_TEXT: Int = TEXT_PRIMARY

    val TITLE_BAR_BACKGROUND: Int = Color(20, 20, 22).rgb
    val TITLE_BAR_TEXT: Int = TEXT_PRIMARY
    val TITLE_BAR_SEPARATOR: Int = MODERN_DIVIDER_COLOR
}